exports.response = [
  {
    algo: "LSA",
    execution_time: 0.07299661636352539,
    summary:
      "[Music].chinese bamboo tree is like other plants.and trees it requires nurturing through.water fertile soil and sunshine.if you plant the tree and give it enough.water the right soil and sunlight you.won't see any visible growth in the.first year.if you continue nurturing it correctly.you won't see any difference for the.second third or fourth year either in.the fifth year something amazing will.happen.the bamboo tree will grow 80 to 90 feet.in just five to six weeks.but let's be serious does the bamboo.really grow 80 to 90 feet in 5-6 weeks.if the bamboo tree did not grow its.roots for a strong foundation in the.first few years it could never grow so.high above the ground so how does this.relate to our lives.we all have dreams and goals you may be.building a career a business learning a.new skill or just creating a better life.in general no matter what your dream or.goal is it's always very difficult to.start with.you may be putting lots of effort in you.may have spent a lot of time but nothing.seems to be happening there are no.visible changes that you would like to.be seeing it would be very easy to give.up on your dreams and goals in the same.way you could with the bamboo tree in.the first four years because there is.nothing to see in terms of visible.growth.also you may not notice the change.instantly but like the network of roots.the growth is happening.remember success doesn't come right away.and every situation and individual are.different.most importantly it requires a strong.foundation working hard towards your.goals and dreams building a solid.internal foundation developing your.inner strength while overcoming.challenges will put you firmly on the.path to success",
    similarity_score: 0.785,
  },
  {
    algo: "TextRank",
    execution_time: 2.1,
    summary:
      "[Music].chinese bamboo tree is like other plants.and trees it requires nurturing through.water fertile soil and sunshine.if you plant the tree and give it enough.water the right soil and sunlight you.won't see any visible growth in the.first year.if you continue nurturing it correctly.you won't see any difference for the.second third or fourth year either in.the fifth year something amazing will.happen.the bamboo tree will grow 80 to 90 feet.in just five to six weeks.but let's be serious does the bamboo.really grow 80 to 90 feet in 5-6 weeks.if the bamboo tree did not grow its.roots for a strong foundation in the.first few years it could never grow so.high above the ground so how does this.relate to our lives.we all have dreams and goals you may be.building a career a business learning a.new skill or just creating a better life.in general no matter what your dream or.goal is it's always very difficult to.start with.you may be putting lots of effort in you.may have spent a lot of time but nothing.seems to be happening there are no.visible changes that you would like to.be seeing it would be very easy to give.up on your dreams and goals in the same.way you could with the bamboo tree in.the first four years because there is.nothing to see in terms of visible.growth.also you may not notice the change.instantly but like the network of roots.the growth is happening.remember success doesn't come right away.and every situation and individual are.different.most importantly it requires a strong.foundation working hard towards your.goals and dreams building a solid.internal foundation developing your.inner strength while overcoming.challenges will put you firmly on the.path to success",
    similarity_score: 0.6103918752987301,
  },
  {
    algo: "Transformer",
    execution_time: 13.333,
    summary:
      " The chinese bamboo tree is like other plants and trees it requires nurturing through water fertile soil and sunshine . If you plant the tree and give it enough water the right soil and sunlight you won't see any visible growth in the first year . The bamboo tree will grow 80 to 90 feet in just five to six weeks .  It would be very easy to give up on your dreams and goals in the same way you could with the bamboo tree in the first four years because there is nothing to see in terms of visible growth . Success doesn't come right away and every situation and individual are different most importantly it requires a strong foundation . ",
    similarity_score: 0.889,
  },
];

// {
// "original_text": "[Music].chinese bamboo tree is like other plants.and trees it requires nurturing through.water fertile soil and sunshine.if you plant the tree and give it enough.water the right soil and sunlight you.won't see any visible growth in the.first year.if you continue nurturing it correctly.you won't see any difference for the.second third or fourth year either in.the fifth year something amazing will.happen.the bamboo tree will grow 80 to 90 feet.in just five to six weeks.but let's be serious does the bamboo.really grow 80 to 90 feet in 5-6 weeks.if the bamboo tree did not grow its.roots for a strong foundation in the.first few years it could never grow so.high above the ground so how does this.relate to our lives.we all have dreams and goals you may be.building a career a business learning a.new skill or just creating a better life.in general no matter what your dream or.goal is it's always very difficult to.start with.you may be putting lots of effort in you.may have spent a lot of time but nothing.seems to be happening there are no.visible changes that you would like to.be seeing it would be very easy to give.up on your dreams and goals in the same.way you could with the bamboo tree in.the first four years because there is.nothing to see in terms of visible.growth.also you may not notice the change.instantly but like the network of roots.the growth is happening.remember success doesn't come right away.and every situation and individual are.different.most importantly it requires a strong.foundation working hard towards your.goals and dreams building a solid.internal foundation developing your.inner strength while overcoming.challenges will put you firmly on the.path to success",
// "response_huggingface": {
// "Execution_time": 211.49116849899292,
// "processed_summary": " The chinese bamboo tree is like other plants and trees it requires nurturing through water fertile soil and sunshine . If you plant the tree and give it enough water the right soil and sunlight you won't see any visible growth in the first year . The bamboo tree will grow 80 to 90 feet in just five to six weeks .  It would be very easy to give up on your dreams and goals in the same way you could with the bamboo tree in the first four years because there is nothing to see in terms of visible growth . Success doesn't come right away and every situation and individual are different most importantly it requires a strong foundation . ",
// "similarity_score": 0.6103918752987301
// },
// "response_lsa": {
// "Execution_time": 0.07299661636352539,
// "processed_summary": "[Music].chinese bamboo tree is like other plants.and trees it requires nurturing through.water fertile soil and sunshine.if you plant the tree and give it enough.water the right soil and sunlight you.won't see any visible growth in the.first year.if you continue nurturing it correctly.you won't see any difference for the.second third or fourth year either in.the fifth year something amazing will.happen.the bamboo tree will grow 80 to 90 feet.in just five to six weeks.but let's be serious does the bamboo.really grow 80 to 90 feet in 5-6 weeks.if the bamboo tree did not grow its.roots for a strong foundation in the.first few years it could never grow so.high above the ground so how does this.relate to our lives.we all have dreams and goals you may be.building a career a business learning a.new skill or just creating a better life.in general no matter what your dream or.goal is it's always very difficult to.start with.you may be putting lots of effort in you.may have spent a lot of time but nothing.seems to be happening there are no.visible changes that you would like to.be seeing it would be very easy to give.up on your dreams and goals in the same.way you could with the bamboo tree in.the first four years because there is.nothing to see in terms of visible.growth.also you may not notice the change.instantly but like the network of roots.the growth is happening.remember success doesn't come right away.and every situation and individual are.different.most importantly it requires a strong.foundation working hard towards your.goals and dreams building a solid.internal foundation developing your.inner strength while overcoming.challenges will put you firmly on the.path to success",
// "similarity_score": 1.0
// },
// "response_textrank": {
// "Execution_time": 0.038001060485839844,
// "processed_summary": "[Music].chinese bamboo tree is like other plants.and trees it requires nurturing through.water fertile soil and sunshine.if you plant the tree and give it enough.water the right soil and sunlight you.won't see any visible growth in the.first year.if you continue nurturing it correctly.you won't see any difference for the.second third or fourth year either in.the fifth year something amazing will.happen.the bamboo tree will grow 80 to 90 feet.in just five to six weeks.but let's be serious does the bamboo.really grow 80 to 90 feet in 5-6 weeks.if the bamboo tree did not grow its.roots for a strong foundation in the.first few years it could never grow so.high above the ground so how does this.relate to our lives.we all have dreams and goals you may be.building a career a business learning a.new skill or just creating a better life.in general no matter what your dream or.goal is it's always very difficult to.start with.you may be putting lots of effort in you.may have spent a lot of time but nothing.seems to be happening there are no.visible changes that you would like to.be seeing it would be very easy to give.up on your dreams and goals in the same.way you could with the bamboo tree in.the first four years because there is.nothing to see in terms of visible.growth.also you may not notice the change.instantly but like the network of roots.the growth is happening.remember success doesn't come right away.and every situation and individual are.different.most importantly it requires a strong.foundation working hard towards your.goals and dreams building a solid.internal foundation developing your.inner strength while overcoming.challenges will put you firmly on the.path to success",
// "similarity_score": 1.0
// }
// }